# Setup
title:        Oropharyngeal-Swab-Sampling-end-effector
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/Oropharyngeal-Swab-Sampling-end-effector"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       MingshanHe
  url:        MingshanHe.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown